### ISSUE TITLE
naming of 'rule' request attribute

### ISSUE THREAD

**Issue by unuseless** [nathancahill/flask-inputs#13]
In order to validate url rules, flask-inputs uses "rule".  In the Flask documentation (http://flask.pocoo.org/docs/0.12/api/#url-route-registrations) these are called "url_rule".

Please consider offering also url_rule in flask-inputs for consistency.

**Comment by nathancahill** [comment]
Good idea. I'd accept this as a PR.

**Comment by unuseless** [comment]
Thanks.
