### ISSUE TITLE
jsonschema isn't specified as a requirement

### ISSUE THREAD

**Issue by aodj** [nathancahill/flask-inputs#17]
`jsonschema` isn't listed in the [`requirements.txt`](https://github.com/nathancahill/flask-inputs/blob/master/requirements.txt) which means you can't use the [example](https://pythonhosted.org/Flask-Inputs/#json-validation) in the documentation.

Weirdly it _is_ listed in the [`requirements-dev.txt`](https://github.com/nathancahill/flask-inputs/blob/master/requirements-dev.txt). It's also only listed in the `tests_require` section in the [`setup.py`](https://github.com/nathancahill/flask-inputs/blob/master/setup.py#L23-L24)

**Comment by nathancahill** [comment]
It's not a requirement because it's optional if you want to use jsonschema validation.
