### ISSUE TITLE
Discuss new feature: return status code after validation

### ISSUE THREAD

**Issue by lqhuang** [nathancahill/flask-inputs#20]
Hey, guys,

Thanks for your effort! I found this package exactly is what I wanted. Here, I want to discuss several improvable functions or missing features.

How do you think about let Flask-Inputs also return the [HTTP status code](https://www.flaskapi.org/api-guide/status-codes/) for error handling.

For now, Flask-Inputs only raise error message when validation failed. eg:

    class CustomInputs(Inputs):
        headers = {
            'Content-Type': [
                AnyOf(
                    ('application/json', ),
                    message="Content-Type of Headers must be 'application/json'",
                ),
            ]
        }

    @app.route('/api', methods=('GET', 'POST')
    def api_inference():
        inputs = CustomInputs(request)

        if not inputs.validate():
            return jsonify(success=False, errors=inputs.errors)

Flask-Inputs works well and return a error message to client, if the request has a wrong `Content-Type`. But the client still would receive status code `200` which indicates that the client's request was successfully received, understood, and accepted (according to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)). Actually, this request was just received but accepted. The correct status code should be `415` indicates that the origin server is refusing to service the request because the payload is in a format not supported.

Hence, what I expected is:

    class CustomInputs(Inputs):
        headers = {
            'Content-Type': [
                AnyOf(
                    ('application/json', ),
                    message="Content-Type of Headers must be 'application/json'",
                ),
            ]
        }

    @app.route('/api', methods=('GET', 'POST')
    def api_inference():
        inputs = CustomInputs(request)

        if not inputs.validate():
            return jsonify(success=False, errors=inputs.errors), inputs.status_code

The major different is in second return variable of last line `inputs.status_code`. This will make both client/server much easier to debug, check and log information.

I think this is really a valuable and necessary function.

Of course, there are also problems would be troubles when implementing this function:

(1) Priority of status code. If there are multiple wrong validations, which one should be returned. Two choices: a. Protocol sequence. Check headers first, then validate json or form or else things defined in HTTP protocol. Return first error status codes. b. Depending on implementation of codes, like follow `valid_attrs = ['args', 'form', 'values', 'cookies', 'headers', 'json', 'rule']` attributes.

(2) The way to define or custom status code for specific validation. Where to define error status code. Here, I provide one solution. eg:

    class CustomInputs(Inputs):
        headers = {
            'Content-Type': [
                AnyOf(
                    ('application/json', ),
                    message="Content-Type of Headers must be 'application/json'",
                    errorcode=415,
                ),
            ]
        }

Now, validaors of Flask-Inputs are depending on `wtforms` packages. If necessary, could we rewrite or reimplement ourself validators based on `wtforms.validators`. (Yeah, sometimes, I ported several validators directly from source codes, becuase I didn't use package `wtforms` in my codes.)

This probably isn't the best way. We can discuss to get a better solution to define status code for each validation.

Thanks for reading. Looking forwarding to knowing your opinions. Or whether developer accept pull request in this new feature.

Regards.

**Comment by nathancahill** [comment]
Thanks for the detailed description! Would it be possible to do this?

```python
    if not inputs.validate():
        return jsonify(success=False, errors=inputs.errors), 415
```

**Comment by lqhuang** [comment]
@nathancahill Hey, thanks for your reply! Yeah, for now, I do it in this way:

    if not inputs.validate():
        return jsonify(success=False, errors=inputs.errors), 415

But I raised a discussion here is trying to find more convenient method to get `status_code`. In this case, I only check `Content-Type`, so when it failed in validation, I know I should return `415` as status code. It's just a minimal example. However, in real codes, we usually want to validate many things like `headers`, `values`, `json`, `cookies`, ... in one input. Not all error inputs correspond to status code `415`.

What I probably wanted is a feature like you can define messages in `inputs.errors`. If validation failed, we could know detail status code. It would be easier to debug in both client and server.
