### ISSUE TITLE
Numeric values

### ISSUE THREAD

**Issue by Gloix** [nathancahill/flask-inputs#5]
Numeric values fail to validate with, for example, NumberRange built-in validator.
Maybe the structure should be kind of like:

```
rules = {
    'age': {type:'integer',
            validators:[DataRequired(u'age is required'), NumberRange(1,120)]}
}
```

and then the internal input representation is a Wtforms IntegerField. This way input is properly coerced.

Another option would be to just directly set `type` equal to any of the field types that Wtforms provides, but I don't know if the "Field" suffix of all the field types would introduce improper naming, since Flask-inputs validates more than form _fields_.
Example:

```
from wtforms.fields import IntegerField

rules = {
    'age': {type:IntegerField,
            validators:[DataRequired(u'age is required'), NumberRange(1,120)]}
}
```

**Comment by songxiaowei112** [comment]
I think you should distinguish between WTF is to Form the Form submission, JSONSCHEMA for json data types.
